#:schema node_modules/wrangler/config-schema.json
name = "next-tailwind-demo"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[pages_build_output_dir]]
value = "out"